<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>JobPlatform.JobPosting.Api</AssemblyName>
    <RootNamespace>JobPlatform.JobPosting.Api</RootNamespace>
    <UserSecretsId>jobplatform-job-posting</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\JobPlatform.JobPosting.Application\JobPlatform.JobPosting.Application.csproj" />
    <ProjectReference Include="..\JobPlatform.JobPosting.Infrastructure\JobPlatform.JobPosting.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\JobPlatform.SharedKernel\JobPlatform.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\JobPlatform.BuildingBlocks.Infrastructure\JobPlatform.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\JobPlatform.BuildingBlocks.Api\JobPlatform.BuildingBlocks.Api.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="JobPlatform.JobPosting.Api.IntegrationTests" />
    <InternalsVisibleTo Include="JobPlatform.JobPosting.ArchitectureTests" />
  </ItemGroup>
</Project>