<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>JobPlatform.GovernmentIntegration.Api</AssemblyName>
    <RootNamespace>JobPlatform.GovernmentIntegration.Api</RootNamespace>
    <UserSecretsId>jobplatform-government-integration</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\JobPlatform.GovernmentIntegration.Application\JobPlatform.GovernmentIntegration.Application.csproj" />
    <ProjectReference Include="..\JobPlatform.GovernmentIntegration.Infrastructure\JobPlatform.GovernmentIntegration.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\JobPlatform.SharedKernel\JobPlatform.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\JobPlatform.BuildingBlocks.Infrastructure\JobPlatform.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\JobPlatform.BuildingBlocks.Api\JobPlatform.BuildingBlocks.Api.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="JobPlatform.GovernmentIntegration.Api.IntegrationTests" />
    <InternalsVisibleTo Include="JobPlatform.GovernmentIntegration.ArchitectureTests" />
  </ItemGroup>
</Project>