using System.Text.Json;
using FluentValidation;
using JobPlatform.Reporting.Domain;
using JobPlatform.SharedKernel.Application.Abstractions;
using JobPlatform.SharedKernel.Application.Ports;
using JobPlatform.SharedKernel.Application.Results;

namespace JobPlatform.Reporting.Application;

// US-3.5.2-08 Labor Market Report: one per calendar month, generated by a scheduled job or on demand, idempotent per period.

public sealed record GetLaborMarketReportQuery(string? Period) : EmploymentRequest, IQuery<LaborMarketReportDto>;

/// <summary>Idempotent: an existing report for the period is returned, never duplicated. Period null = the previous calendar month.</summary>
public sealed record GenerateLaborMarketReportCommand(string? Period) : EmploymentCommandRequest, ICommand<LaborMarketReportDto>, IConflictAwareCommand
{
    public string UniqueViolationErrorCode => ReportingErrorCodes.EmploymentInvalidField;
}

/// <summary>Scheduled variant (no caller, no access check): generates the report of the previous month when it does not exist yet.</summary>
public sealed record RunScheduledLaborMarketReportCommand : ICommand<LaborMarketReportDto>;

public sealed class LaborMarketPeriodValidators : AbstractValidator<GetLaborMarketReportQuery>
{
    public LaborMarketPeriodValidators() =>
        RuleFor(x => x.Period).Must(p => p is null || LaborMarketReport.TryParsePeriod(p, out _, out _)).WithErrorCode("VAL.Period.Invalid");
}

public sealed class GenerateLaborMarketReportValidator : AbstractValidator<GenerateLaborMarketReportCommand>
{
    public GenerateLaborMarketReportValidator() =>
        RuleFor(x => x.Period).Must(p => p is null || LaborMarketReport.TryParsePeriod(p, out _, out _)).WithErrorCode("VAL.Period.Invalid");
}

/// <summary>Builds the content of a labor-market report from the analytics store (counts only; every breakdown honours small-cell suppression).</summary>
public sealed class LaborMarketReportBuilder
{
    private static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);

    private readonly IAnalyticsQueryService _analytics;
    private readonly StatisticsPolicy _policy;

    public LaborMarketReportBuilder(IAnalyticsQueryService analytics, StatisticsPolicy policy)
    {
        _analytics = analytics;
        _policy = policy;
    }

    public async Task<string> BuildJsonAsync(string period, CancellationToken ct)
    {
        LaborMarketReport.TryParsePeriod(period, out var start, out var end);
        var postings = await _analytics.PostingsAsync(start, end, 200_000, ct);
        var registrations = await _analytics.RegistrationsAsync(start, end, 200_000, ct);
        var skills = await _analytics.SkillsAsync(start, end, 200_000, ct);

        IReadOnlyList<object> Top(IEnumerable<string?> values) => values.GroupBy(StatisticsCalculator.Bucket)
            .Where(g => !_policy.IsSuppressed(g.Count())).OrderByDescending(g => g.Count()).ThenBy(g => g.Key).Take(10)
            .Select(g => (object)new { name = g.Key, count = g.Count() }).ToList();

        var withSalary = postings.Where(p => p.SalaryMin is not null || p.SalaryMax is not null).ToList();
        var content = new
        {
            period,
            insufficientData = _policy.IsInsufficient(postings.Count),
            postings = new { total = postings.Count, active = postings.Count(p => p.Status.Equals("active", StringComparison.OrdinalIgnoreCase)) },
            topIndustries = Top(postings.Select(p => p.Category)),
            topLocations = Top(postings.Select(p => p.Location)),
            registrations = new
            {
                jobSeekers = registrations.Count(r => r.Milestone == "AccountCreated" && r.ActorType == "JobSeeker"),
                employers = registrations.Count(r => r.Milestone == "AccountCreated" && r.ActorType == "Employer")
            },
            topSkillsInDemand = skills.Where(s => s.Side == FactSkillDemand.Demand).GroupBy(s => s.Skill).Where(g => !_policy.IsSuppressed(g.Count()))
                .OrderByDescending(g => g.Count()).ThenBy(g => g.Key).Take(10).Select(g => new { name = g.Key, count = g.Count() }).ToList(),
            salary = _policy.IsInsufficient(withSalary.Count)
                ? null
                : new { samples = withSalary.Count, average = Math.Round(withSalary.Average(p => StatisticsCalculator.Midpoint(p.SalaryMin, p.SalaryMax)), 2) }
        };
        return JsonSerializer.Serialize(content, Json);
    }
}

internal sealed class LaborMarketHandlers :
    IQueryHandler<GetLaborMarketReportQuery, LaborMarketReportDto>,
    ICommandHandler<GenerateLaborMarketReportCommand, LaborMarketReportDto>,
    ICommandHandler<RunScheduledLaborMarketReportCommand, LaborMarketReportDto>
{
    private readonly IReportAccessGuard _guard;
    private readonly ILaborMarketReportRepository _reports;
    private readonly LaborMarketReportBuilder _builder;
    private readonly ICurrentUser _user;
    private readonly TimeProvider _clock;

    public LaborMarketHandlers(IReportAccessGuard guard, ILaborMarketReportRepository reports, LaborMarketReportBuilder builder, ICurrentUser user, TimeProvider clock)
    {
        _guard = guard;
        _reports = reports;
        _builder = builder;
        _user = user;
        _clock = clock;
    }

    private DateTime Now => _clock.GetUtcNow().UtcDateTime;

    private string PreviousMonth() => LaborMarketReport.PeriodOf(new DateTime(Now.Year, Now.Month, 1, 0, 0, 0, DateTimeKind.Utc).AddMonths(-1));

    public async Task<Result<LaborMarketReportDto>> Handle(GetLaborMarketReportQuery request, CancellationToken ct)
    {
        var access = await _guard.EnsureAsync(ReportCategory.EmploymentStatistics, nameof(GetLaborMarketReportQuery), ct);
        if (access.IsFailure)
        {
            return access.Error!;
        }

        var period = request.Period ?? PreviousMonth();
        var report = await _reports.GetByPeriodAsync(period, ct);
        return report is null
            ? Error.NotFound(ReportingErrorCodes.NotFound, $"No labor-market report exists for {period}.")
            : ToDto(report, true);
    }

    public async Task<Result<LaborMarketReportDto>> Handle(GenerateLaborMarketReportCommand request, CancellationToken ct)
    {
        var access = await _guard.EnsureAsync(ReportCategory.EmploymentStatistics, nameof(GenerateLaborMarketReportCommand), ct);
        if (access.IsFailure)
        {
            return access.Error!;
        }

        return await GenerateAsync(request.Period ?? PreviousMonth(), _user.UserId, ct);
    }

    public Task<Result<LaborMarketReportDto>> Handle(RunScheduledLaborMarketReportCommand request, CancellationToken ct) => GenerateAsync(PreviousMonth(), null, ct);

    private async Task<Result<LaborMarketReportDto>> GenerateAsync(string period, Guid? by, CancellationToken ct)
    {
        var existing = await _reports.GetByPeriodAsync(period, ct);
        if (existing is not null)
        {
            return ToDto(existing, true);
        }

        var report = LaborMarketReport.Generate(period, await _builder.BuildJsonAsync(period, ct), by, Now);
        _reports.Add(report);
        return ToDto(report, false);
    }

    private static LaborMarketReportDto ToDto(LaborMarketReport r, bool existing) =>
        new(r.Id, r.Period, r.GeneratedAtUtc, JsonDocument.Parse(r.ContentJson).RootElement.Clone(), existing);
}
