<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>JobPlatform.PlatformAdministration.Domain</AssemblyName>
    <RootNamespace>JobPlatform.PlatformAdministration.Domain</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\JobPlatform.SharedKernel\JobPlatform.SharedKernel.csproj" />
  </ItemGroup>
</Project>