// <auto-generated />
using System;
using JobPlatform.HelpContent.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobPlatform.HelpContent.Infrastructure.Migrations
{
    [DbContext(typeof(HelpContentDbContext))]
    [Migration("20260927144222_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("content")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobPlatform.BuildingBlocks.Infrastructure.Persistence.IdempotencyKeyRecord", b =>
                {
                    b.Property<string>("Scope")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Scope", "Key");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("IX_IdempotencyKeys_ExpiresAtUtc");

                    b.ToTable("IdempotencyKeys", "messaging");
                });

            modelBuilder.Entity("JobPlatform.BuildingBlocks.Infrastructure.Persistence.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("NextAttemptUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReceivedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("MessageId", "ConsumerName");

                    b.HasIndex("Status", "NextAttemptUtc")
                        .HasDatabaseName("IX_InboxMessages_Status_NextAttemptUtc");

                    b.ToTable("InboxMessages", "messaging");
                });

            modelBuilder.Entity("JobPlatform.BuildingBlocks.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("AggregateVersion")
                        .HasColumnType("bigint");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("NextAttemptUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextAttemptUtc")
                        .HasDatabaseName("IX_OutboxMessages_Status_NextAttemptUtc");

                    b.ToTable("OutboxMessages", "messaging");
                });

            modelBuilder.Entity("JobPlatform.HelpContent.Domain.CompanyProfilePage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployerAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Highlights")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HighlightsJson");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("EmployerAccountId")
                        .IsUnique()
                        .HasDatabaseName("UQ_CompanyProfilePages_EmployerAccountId");

                    b.ToTable("CompanyProfilePages", "content");
                });

            modelBuilder.Entity("JobPlatform.HelpContent.Domain.ContentCategorization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CategoryIdsJson");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TagsJson");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ContentCategorizations_ArticleId");

                    b.ToTable("ContentCategorizations", "content");
                });

            modelBuilder.Entity("JobPlatform.HelpContent.Domain.ContentCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.ToTable("ContentCategories", "content");
                });

            modelBuilder.Entity("JobPlatform.HelpContent.Domain.ContextHelpMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HelpContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PageKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("PageKey")
                        .IsUnique()
                        .HasDatabaseName("UQ_ContextHelpMappings_PageKey");

                    b.ToTable("ContextHelpMappings", "content");
                });

            modelBuilder.Entity("JobPlatform.HelpContent.Domain.HelpContent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("int");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.ToTable("HelpContents", "content");
                });

            modelBuilder.Entity("JobPlatform.HelpContent.Domain.HelpContentOrganization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HelpContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RolesJson");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("HelpContentId")
                        .IsUnique()
                        .HasDatabaseName("UQ_HelpContentOrganizations_HelpContentId");

                    b.ToTable("HelpContentOrganizations", "content");
                });

            modelBuilder.Entity("JobPlatform.HelpContent.Domain.HelpFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("HelpContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("HelpContentId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_HelpFeedback_Content_User");

                    b.ToTable("HelpFeedback", "content");
                });

            modelBuilder.Entity("JobPlatform.HelpContent.Domain.HelpTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.ToTable("HelpTopics", "content");
                });

            modelBuilder.Entity("JobPlatform.HelpContent.Domain.NewsArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("IX_NewsArticles_ContentHash");

                    b.HasIndex("Status", "PublishedAtUtc")
                        .HasDatabaseName("IX_NewsArticles_Status_PublishedAt");

                    b.ToTable("NewsArticles", "content");
                });

            modelBuilder.Entity("JobPlatform.HelpContent.Domain.TutorialProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TutorialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "TutorialId")
                        .IsUnique()
                        .HasDatabaseName("UQ_TutorialProgress_User_Tutorial");

                    b.ToTable("TutorialProgress", "content");
                });

            modelBuilder.Entity("JobPlatform.HelpContent.Domain.CompanyProfilePage", b =>
                {
                    b.OwnsOne("JobPlatform.HelpContent.Domain.Common.LocalizedText", "Background", b1 =>
                        {
                            b1.Property<Guid>("CompanyProfilePageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Ar")
                                .HasMaxLength(50000)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("BackgroundAr");

                            b1.Property<string>("En")
                                .HasMaxLength(50000)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("BackgroundEn");

                            b1.HasKey("CompanyProfilePageId");

                            b1.ToTable("CompanyProfilePages", "content");

                            b1.WithOwner()
                                .HasForeignKey("CompanyProfilePageId");
                        });

                    b.Navigation("Background")
                        .IsRequired();
                });

            modelBuilder.Entity("JobPlatform.HelpContent.Domain.ContentCategory", b =>
                {
                    b.OwnsOne("JobPlatform.HelpContent.Domain.Common.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<Guid>("ContentCategoryId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Ar")
                                .HasMaxLength(50000)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("NameAr");

                            b1.Property<string>("En")
                                .HasMaxLength(50000)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("NameEn");

                            b1.HasKey("ContentCategoryId");

                            b1.ToTable("ContentCategories", "content");

                            b1.WithOwner()
                                .HasForeignKey("ContentCategoryId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("JobPlatform.HelpContent.Domain.HelpContent", b =>
                {
                    b.OwnsMany("JobPlatform.HelpContent.Domain.HelpContentVersion", "Versions", b1 =>
                        {
                            b1.Property<Guid>("HelpContentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("VersionNo");

                            b1.Property<DateTime>("EditedAtUtc")
                                .HasColumnType("datetime2");

                            b1.Property<Guid>("EditedBy")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("HelpContentId", "Id");

                            b1.ToTable("HelpContentVersions", "content");

                            b1.WithOwner()
                                .HasForeignKey("HelpContentId");

                            b1.OwnsOne("JobPlatform.HelpContent.Domain.Common.LocalizedText", "Body", b2 =>
                                {
                                    b2.Property<Guid>("HelpContentVersionHelpContentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("HelpContentVersionId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Ar")
                                        .HasMaxLength(50000)
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("BodyAr");

                                    b2.Property<string>("En")
                                        .HasMaxLength(50000)
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("BodyEn");

                                    b2.HasKey("HelpContentVersionHelpContentId", "HelpContentVersionId");

                                    b2.ToTable("HelpContentVersions", "content");

                                    b2.WithOwner()
                                        .HasForeignKey("HelpContentVersionHelpContentId", "HelpContentVersionId");
                                });

                            b1.OwnsOne("JobPlatform.HelpContent.Domain.Common.LocalizedText", "Title", b2 =>
                                {
                                    b2.Property<Guid>("HelpContentVersionHelpContentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("HelpContentVersionId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Ar")
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)")
                                        .HasColumnName("TitleAr");

                                    b2.Property<string>("En")
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)")
                                        .HasColumnName("TitleEn");

                                    b2.HasKey("HelpContentVersionHelpContentId", "HelpContentVersionId");

                                    b2.ToTable("HelpContentVersions", "content");

                                    b2.WithOwner()
                                        .HasForeignKey("HelpContentVersionHelpContentId", "HelpContentVersionId");
                                });

                            b1.Navigation("Body")
                                .IsRequired();

                            b1.Navigation("Title")
                                .IsRequired();
                        });

                    b.OwnsMany("JobPlatform.HelpContent.Domain.HelpMediaItem", "Media", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CaptionsRef")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<Guid>("HelpContentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("StorageKey")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<string>("TextAlternative")
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)");

                            b1.HasKey("Id");

                            b1.HasIndex("HelpContentId")
                                .HasDatabaseName("IX_HelpMedia_HelpContentId");

                            b1.ToTable("HelpMedia", "content");

                            b1.WithOwner()
                                .HasForeignKey("HelpContentId");
                        });

                    b.Navigation("Media");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("JobPlatform.HelpContent.Domain.HelpTopic", b =>
                {
                    b.OwnsOne("JobPlatform.HelpContent.Domain.Common.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<Guid>("HelpTopicId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Ar")
                                .HasMaxLength(50000)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("NameAr");

                            b1.Property<string>("En")
                                .HasMaxLength(50000)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("NameEn");

                            b1.HasKey("HelpTopicId");

                            b1.ToTable("HelpTopics", "content");

                            b1.WithOwner()
                                .HasForeignKey("HelpTopicId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("JobPlatform.HelpContent.Domain.NewsArticle", b =>
                {
                    b.OwnsOne("JobPlatform.HelpContent.Domain.Common.LocalizedText", "Body", b1 =>
                        {
                            b1.Property<Guid>("NewsArticleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Ar")
                                .HasMaxLength(50000)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("BodyAr");

                            b1.Property<string>("En")
                                .HasMaxLength(50000)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("BodyEn");

                            b1.HasKey("NewsArticleId");

                            b1.ToTable("NewsArticles", "content");

                            b1.WithOwner()
                                .HasForeignKey("NewsArticleId");
                        });

                    b.OwnsOne("JobPlatform.HelpContent.Domain.Common.LocalizedText", "Title", b1 =>
                        {
                            b1.Property<Guid>("NewsArticleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Ar")
                                .HasMaxLength(50000)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("TitleAr");

                            b1.Property<string>("En")
                                .HasMaxLength(50000)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("TitleEn");

                            b1.HasKey("NewsArticleId");

                            b1.ToTable("NewsArticles", "content");

                            b1.WithOwner()
                                .HasForeignKey("NewsArticleId");
                        });

                    b.OwnsMany("JobPlatform.HelpContent.Domain.NewsMediaItem", "Media", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AltText")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<Guid>("NewsArticleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.HasKey("Id");

                            b1.HasIndex("NewsArticleId")
                                .HasDatabaseName("IX_NewsMedia_NewsArticleId");

                            b1.ToTable("NewsMedia", "content");

                            b1.WithOwner()
                                .HasForeignKey("NewsArticleId");

                            b1.OwnsOne("JobPlatform.HelpContent.Domain.NewsMediaFile", "File", b2 =>
                                {
                                    b2.Property<Guid>("NewsMediaItemId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("ContentType")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)")
                                        .HasColumnName("ContentType");

                                    b2.Property<long>("SizeBytes")
                                        .HasColumnType("bigint")
                                        .HasColumnName("SizeBytes");

                                    b2.Property<string>("StorageKey")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("nvarchar(500)")
                                        .HasColumnName("StorageKey");

                                    b2.HasKey("NewsMediaItemId");

                                    b2.ToTable("NewsMedia", "content");

                                    b2.WithOwner()
                                        .HasForeignKey("NewsMediaItemId");
                                });

                            b1.Navigation("File")
                                .IsRequired();
                        });

                    b.Navigation("Body")
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("Title")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
