<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>JobPlatform.JobSeekerProfile.Domain.UnitTests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/Services/JobSeekerProfile/JobPlatform.JobSeekerProfile.Domain/JobPlatform.JobSeekerProfile.Domain.csproj" />
    <ProjectReference Include="../../../src/BuildingBlocks/JobPlatform.SharedKernel/JobPlatform.SharedKernel.csproj" />
  </ItemGroup>
</Project>