// <auto-generated />
using System;
using JobPlatform.AiMatching.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobPlatform.AiMatching.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AiMatchingDbContext))]
    [Migration("20260921143837_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("matching")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobPlatform.AiMatching.Domain.CandidateShortlist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ComputedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ConfigVersion")
                        .HasColumnType("int");

                    b.Property<Guid>("EmployerAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ItemsJson");

                    b.Property<Guid>("JobPostingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestedSize")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("JobPostingId")
                        .HasDatabaseName("IX_CandidateShortlists_Posting");

                    b.ToTable("CandidateShortlists", "matching");
                });

            modelBuilder.Entity("JobPlatform.AiMatching.Domain.ConfigurationHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ConfigVersion")
                        .HasColumnType("int");

                    b.Property<Guid?>("ConfigurationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("LowConfidenceThresholdPercent")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("MatchThresholdPercent")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("ShortlistSize")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConfigVersion")
                        .HasDatabaseName("IX_ConfigurationHistory_Version");

                    b.HasIndex("ConfigurationId");

                    b.ToTable("ConfigurationHistory", "matching");
                });

            modelBuilder.Entity("JobPlatform.AiMatching.Domain.JobRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ComputedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ItemsJson");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "ComputedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_JobRecommendations_Profile_ComputedAt");

                    b.ToTable("JobRecommendations", "matching");
                });

            modelBuilder.Entity("JobPlatform.AiMatching.Domain.JobSemantics", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("JobPostingId");

                    b.Property<DateTime>("AnalyzedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CategoriesJson");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("ExperienceLevels")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LevelsJson");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<bool>("LowConfidence")
                        .HasColumnType("bit");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("PostingVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("RequiredSkills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SkillsJson");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SemanticsVersion")
                        .HasColumnType("int");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.ToTable("JobSemantics", "matching");
                });

            modelBuilder.Entity("JobPlatform.AiMatching.Domain.KnownPosting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("JobPostingId");

                    b.Property<Guid>("EmployerAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("LastEventVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("Suspended")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployerAccountId", "Status")
                        .HasDatabaseName("IX_KnownPostings_Employer_Status");

                    b.ToTable("KnownPostings", "matching");
                });

            modelBuilder.Entity("JobPlatform.AiMatching.Domain.KnownProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProfileId");

                    b.Property<long>("LastEventVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid>("OwnerAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Standing")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAccountId")
                        .IsUnique()
                        .HasDatabaseName("UQ_KnownProfiles_Owner");

                    b.ToTable("KnownProfiles", "matching");
                });

            modelBuilder.Entity("JobPlatform.AiMatching.Domain.MatchScore", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Breakdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BreakdownJson");

                    b.Property<DateTime>("ComputedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ConfigVersion")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("JobPostingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("PostingVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ProfileVersion")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("Score")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("JobPostingId", "Score")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_MatchScores_Posting_Score");

                    b.HasIndex("ProfileId", "JobPostingId")
                        .IsUnique()
                        .HasDatabaseName("UQ_MatchScores_Profile_Posting");

                    b.HasIndex("ProfileId", "Score")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_MatchScores_Profile_Score");

                    b.ToTable("MatchScores", "matching");
                });

            modelBuilder.Entity("JobPlatform.AiMatching.Domain.MatchingConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ConfigVersion")
                        .HasColumnType("int");

                    b.Property<decimal>("LowConfidenceThresholdPercent")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("MatchThresholdPercent")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("ShortlistSize")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.ToTable("MatchingConfigurations", "matching");
                });

            modelBuilder.Entity("JobPlatform.AiMatching.Domain.MatchingWorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("NextAttemptUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "EntityId")
                        .IsUnique()
                        .HasDatabaseName("UQ_WorkItems_Pending")
                        .HasFilter("[Status] = 'Pending'");

                    b.HasIndex("Status", "NextAttemptUtc")
                        .HasDatabaseName("IX_WorkItems_Status_NextAttempt");

                    b.ToTable("WorkItems", "matching");
                });

            modelBuilder.Entity("JobPlatform.AiMatching.Domain.ParsedField", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("NeedsReview")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ResumeParsedDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ResumeParsedDataId");

                    b.ToTable("ParsedFields", "matching");
                });

            modelBuilder.Entity("JobPlatform.AiMatching.Domain.ParsedProfileData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OwnerAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAccountId")
                        .HasDatabaseName("IX_ParsedProfileData_Owner");

                    b.HasIndex("ProfileId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ParsedProfileData_Profile");

                    b.ToTable("ParsedProfileData", "matching");
                });

            modelBuilder.Entity("JobPlatform.AiMatching.Domain.ProfileField", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("NeedsReview")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ParsedProfileDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParsedProfileDataId");

                    b.ToTable("ProfileFields", "matching");
                });

            modelBuilder.Entity("JobPlatform.AiMatching.Domain.ResumeParsedData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<bool>("LanguageFlagged")
                        .HasColumnType("bit");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SkillsJson");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid?>("SupersededBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("IX_ResumeParsedData_Profile");

                    b.HasIndex("ResumeId", "Sha256")
                        .IsUnique()
                        .HasDatabaseName("UQ_ResumeParsedData_Resume_Sha256");

                    b.ToTable("ResumeParsedData", "matching");
                });

            modelBuilder.Entity("JobPlatform.AiMatching.Domain.SkillMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CanonicalCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("ExtractedTerm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsFreeText")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedsReview")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SkillStandardizationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SkillStandardizationId");

                    b.ToTable("SkillMappings", "matching");
                });

            modelBuilder.Entity("JobPlatform.AiMatching.Domain.SkillStandardization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ResumeParsedDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("TaxonomyVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("ResumeParsedDataId")
                        .HasDatabaseName("IX_SkillStandardizations_ResumeParsedData");

                    b.HasIndex("TaxonomyVersion")
                        .HasDatabaseName("IX_SkillStandardizations_TaxonomyVersion");

                    b.ToTable("SkillStandardizations", "matching");
                });

            modelBuilder.Entity("JobPlatform.AiMatching.Infrastructure.Persistence.EmbeddingRecord", b =>
                {
                    b.Property<string>("EntityType")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Vector")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("EntityType", "EntityId");

                    b.ToTable("Embeddings", "matching");
                });

            modelBuilder.Entity("JobPlatform.BuildingBlocks.Infrastructure.Persistence.IdempotencyKeyRecord", b =>
                {
                    b.Property<string>("Scope")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Scope", "Key");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("IX_IdempotencyKeys_ExpiresAtUtc");

                    b.ToTable("IdempotencyKeys", "messaging");
                });

            modelBuilder.Entity("JobPlatform.BuildingBlocks.Infrastructure.Persistence.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("NextAttemptUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReceivedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("MessageId", "ConsumerName");

                    b.HasIndex("Status", "NextAttemptUtc")
                        .HasDatabaseName("IX_InboxMessages_Status_NextAttemptUtc");

                    b.ToTable("InboxMessages", "messaging");
                });

            modelBuilder.Entity("JobPlatform.BuildingBlocks.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("AggregateVersion")
                        .HasColumnType("bigint");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("NextAttemptUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextAttemptUtc")
                        .HasDatabaseName("IX_OutboxMessages_Status_NextAttemptUtc");

                    b.ToTable("OutboxMessages", "messaging");
                });

            modelBuilder.Entity("JobPlatform.AiMatching.Domain.ConfigurationHistoryEntry", b =>
                {
                    b.HasOne("JobPlatform.AiMatching.Domain.MatchingConfiguration", null)
                        .WithMany("History")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("JobPlatform.AiMatching.Domain.CriterionWeights", "Weights", b1 =>
                        {
                            b1.Property<Guid>("ConfigurationHistoryEntryId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Education")
                                .HasPrecision(6, 2)
                                .HasColumnType("decimal(6,2)")
                                .HasColumnName("WeightEducation");

                            b1.Property<decimal>("Experience")
                                .HasPrecision(6, 2)
                                .HasColumnType("decimal(6,2)")
                                .HasColumnName("WeightExperience");

                            b1.Property<decimal>("Location")
                                .HasPrecision(6, 2)
                                .HasColumnType("decimal(6,2)")
                                .HasColumnName("WeightLocation");

                            b1.Property<decimal>("Salary")
                                .HasPrecision(6, 2)
                                .HasColumnType("decimal(6,2)")
                                .HasColumnName("WeightSalary");

                            b1.Property<decimal>("SkillOverlap")
                                .HasPrecision(6, 2)
                                .HasColumnType("decimal(6,2)")
                                .HasColumnName("WeightSkillOverlap");

                            b1.Property<decimal>("Training")
                                .HasPrecision(6, 2)
                                .HasColumnType("decimal(6,2)")
                                .HasColumnName("WeightTraining");

                            b1.HasKey("ConfigurationHistoryEntryId");

                            b1.ToTable("ConfigurationHistory", "matching");

                            b1.WithOwner()
                                .HasForeignKey("ConfigurationHistoryEntryId");
                        });

                    b.Navigation("Weights")
                        .IsRequired();
                });

            modelBuilder.Entity("JobPlatform.AiMatching.Domain.MatchingConfiguration", b =>
                {
                    b.OwnsOne("JobPlatform.AiMatching.Domain.CriterionWeights", "Weights", b1 =>
                        {
                            b1.Property<Guid>("MatchingConfigurationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Education")
                                .HasPrecision(6, 2)
                                .HasColumnType("decimal(6,2)")
                                .HasColumnName("WeightEducation");

                            b1.Property<decimal>("Experience")
                                .HasPrecision(6, 2)
                                .HasColumnType("decimal(6,2)")
                                .HasColumnName("WeightExperience");

                            b1.Property<decimal>("Location")
                                .HasPrecision(6, 2)
                                .HasColumnType("decimal(6,2)")
                                .HasColumnName("WeightLocation");

                            b1.Property<decimal>("Salary")
                                .HasPrecision(6, 2)
                                .HasColumnType("decimal(6,2)")
                                .HasColumnName("WeightSalary");

                            b1.Property<decimal>("SkillOverlap")
                                .HasPrecision(6, 2)
                                .HasColumnType("decimal(6,2)")
                                .HasColumnName("WeightSkillOverlap");

                            b1.Property<decimal>("Training")
                                .HasPrecision(6, 2)
                                .HasColumnType("decimal(6,2)")
                                .HasColumnName("WeightTraining");

                            b1.HasKey("MatchingConfigurationId");

                            b1.ToTable("MatchingConfigurations", "matching");

                            b1.WithOwner()
                                .HasForeignKey("MatchingConfigurationId");
                        });

                    b.Navigation("Weights")
                        .IsRequired();
                });

            modelBuilder.Entity("JobPlatform.AiMatching.Domain.ParsedField", b =>
                {
                    b.HasOne("JobPlatform.AiMatching.Domain.ResumeParsedData", null)
                        .WithMany("Fields")
                        .HasForeignKey("ResumeParsedDataId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JobPlatform.AiMatching.Domain.ProfileField", b =>
                {
                    b.HasOne("JobPlatform.AiMatching.Domain.ParsedProfileData", null)
                        .WithMany("Fields")
                        .HasForeignKey("ParsedProfileDataId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JobPlatform.AiMatching.Domain.SkillMapping", b =>
                {
                    b.HasOne("JobPlatform.AiMatching.Domain.SkillStandardization", null)
                        .WithMany("Mappings")
                        .HasForeignKey("SkillStandardizationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JobPlatform.AiMatching.Domain.MatchingConfiguration", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("JobPlatform.AiMatching.Domain.ParsedProfileData", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("JobPlatform.AiMatching.Domain.ResumeParsedData", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("JobPlatform.AiMatching.Domain.SkillStandardization", b =>
                {
                    b.Navigation("Mappings");
                });
#pragma warning restore 612, 618
        }
    }
}
