<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>JobPlatform.HelpContent.Infrastructure</AssemblyName>
    <RootNamespace>JobPlatform.HelpContent.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\JobPlatform.HelpContent.Application\JobPlatform.HelpContent.Application.csproj" />
    <ProjectReference Include="..\JobPlatform.HelpContent.Domain\JobPlatform.HelpContent.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\JobPlatform.SharedKernel\JobPlatform.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\JobPlatform.BuildingBlocks.Infrastructure\JobPlatform.BuildingBlocks.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="JobPlatform.HelpContent.Infrastructure.IntegrationTests" />
    <InternalsVisibleTo Include="JobPlatform.HelpContent.Api.IntegrationTests" />
  </ItemGroup>
</Project>