// <auto-generated />
using System;
using JobPlatform.Reporting.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobPlatform.Reporting.Infrastructure.Migrations
{
    [DbContext(typeof(ReportingDbContext))]
    partial class ReportingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reporting")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobPlatform.BuildingBlocks.Infrastructure.Persistence.IdempotencyKeyRecord", b =>
                {
                    b.Property<string>("Scope")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Scope", "Key");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("IX_IdempotencyKeys_ExpiresAtUtc");

                    b.ToTable("IdempotencyKeys", "messaging");
                });

            modelBuilder.Entity("JobPlatform.BuildingBlocks.Infrastructure.Persistence.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("NextAttemptUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReceivedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("MessageId", "ConsumerName");

                    b.HasIndex("Status", "NextAttemptUtc")
                        .HasDatabaseName("IX_InboxMessages_Status_NextAttemptUtc");

                    b.ToTable("InboxMessages", "messaging");
                });

            modelBuilder.Entity("JobPlatform.BuildingBlocks.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("AggregateVersion")
                        .HasColumnType("bigint");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("NextAttemptUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextAttemptUtc")
                        .HasDatabaseName("IX_OutboxMessages_Status_NextAttemptUtc");

                    b.ToTable("OutboxMessages", "messaging");
                });

            modelBuilder.Entity("JobPlatform.Reporting.Domain.ActivityLogRetentionPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LegalMinimumMonths")
                        .HasColumnType("int");

                    b.Property<int>("RetentionMonths")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.ToTable("RetentionPolicy", "config");
                });

            modelBuilder.Entity("JobPlatform.Reporting.Domain.AggDaily", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Day", "Metric")
                        .IsUnique()
                        .HasDatabaseName("UQ_AggDaily_Day_Metric");

                    b.ToTable("AggDaily", "reporting");
                });

            modelBuilder.Entity("JobPlatform.Reporting.Domain.FactEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ActorKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceBc")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasDatabaseName("UQ_FactEvent_MessageId");

                    b.HasIndex("OccurredAtUtc", "ActivityType")
                        .HasDatabaseName("IX_FactEvent_OccurredAt_Activity");

                    b.ToTable("FactEvent", "reporting");
                });

            modelBuilder.Entity("JobPlatform.Reporting.Domain.FactJobPosting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FirstSeenAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasDetails")
                        .HasColumnType("bit");

                    b.Property<long>("LastVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("SalaryMax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SalaryMin")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("StatusChangedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("FirstSeenAtUtc")
                        .HasDatabaseName("IX_FactJobPosting_FirstSeen");

                    b.HasIndex("Category", "Location")
                        .HasDatabaseName("IX_FactJobPosting_Category_Location");

                    b.ToTable("FactJobPosting", "reporting");
                });

            modelBuilder.Entity("JobPlatform.Reporting.Domain.FactMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConfigVersion")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("ItemCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("JobPostingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Score")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("IX_FactMatch_OccurredAt");

                    b.ToTable("FactMatch", "reporting");
                });

            modelBuilder.Entity("JobPlatform.Reporting.Domain.FactNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("IX_FactNotification_OccurredAt");

                    b.ToTable("FactNotification", "reporting");
                });

            modelBuilder.Entity("JobPlatform.Reporting.Domain.FactOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("JobPostingId");

                    b.Property<DateTime>("FirstShortlistedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("FitCount")
                        .HasColumnType("int");

                    b.Property<decimal>("FitSum")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("FollowUps")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Shortlisted")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FirstShortlistedAtUtc")
                        .HasDatabaseName("IX_FactOutcome_FirstShortlisted");

                    b.ToTable("FactOutcome", "reporting");
                });

            modelBuilder.Entity("JobPlatform.Reporting.Domain.FactRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Governorate")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Milestone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasDatabaseName("UQ_FactRegistration_MessageId");

                    b.HasIndex("OccurredAtUtc", "Milestone")
                        .HasDatabaseName("IX_FactRegistration_OccurredAt_Milestone");

                    b.ToTable("FactRegistration", "reporting");
                });

            modelBuilder.Entity("JobPlatform.Reporting.Domain.FactSkillDemand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Skill")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("IX_FactSkillDemand_OccurredAt");

                    b.HasIndex("Skill", "Side", "SubjectId")
                        .IsUnique()
                        .HasDatabaseName("UQ_FactSkillDemand_Skill_Side_Subject");

                    b.ToTable("FactSkillDemand", "reporting");
                });

            modelBuilder.Entity("JobPlatform.Reporting.Domain.FactSystemMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("SampledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("Metric", "SampledAtUtc")
                        .HasDatabaseName("IX_FactSystemMetric_Metric_SampledAt");

                    b.ToTable("FactSystemMetric", "reporting");
                });

            modelBuilder.Entity("JobPlatform.Reporting.Domain.LaborMarketReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("GeneratedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("RetainUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("Period")
                        .IsUnique()
                        .HasDatabaseName("UQ_LaborMarketReports_Period");

                    b.ToTable("LaborMarketReports", "config");
                });

            modelBuilder.Entity("JobPlatform.Reporting.Domain.PerformanceAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("RaisedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RetainUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal>("Threshold")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("RetainUntilUtc")
                        .HasDatabaseName("IX_PerformanceAlerts_Retention");

                    b.HasIndex("RuleId", "RaisedAtUtc")
                        .HasDatabaseName("IX_PerformanceAlerts_Rule_RaisedAt");

                    b.ToTable("PerformanceAlerts", "config");
                });

            modelBuilder.Entity("JobPlatform.Reporting.Domain.PerformanceAlertRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comparator")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal>("Threshold")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.Property<int>("WindowMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PerformanceAlertRules", "config");
                });

            modelBuilder.Entity("JobPlatform.Reporting.Domain.ReportAccessDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Allowed")
                        .HasColumnType("bit");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("DecidedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Request")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("DecidedAtUtc")
                        .HasDatabaseName("IX_ReportAccessDecisions_DecidedAt");

                    b.ToTable("ReportAccessDecisions", "config");
                });

            modelBuilder.Entity("JobPlatform.Reporting.Domain.ReportAccessRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoriesCsv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("Role")
                        .IsUnique()
                        .HasDatabaseName("UQ_ReportAccessRules_Role");

                    b.ToTable("ReportAccessRules", "config");
                });

            modelBuilder.Entity("JobPlatform.Reporting.Domain.ReportExport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("ParametersHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RefKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResultRef")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("RequestedBy", "ParametersHash")
                        .IsUnique()
                        .HasDatabaseName("UQ_ReportExports_Running")
                        .HasFilter("[Status] IN ('Queued','Generating')");

                    b.ToTable("ReportExports", "config");
                });

            modelBuilder.Entity("JobPlatform.Reporting.Domain.ReportExportFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ExportId");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ReportExportFiles", "config");
                });

            modelBuilder.Entity("JobPlatform.Reporting.Domain.ReportSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CronText")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastRunAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("NextRunAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecipientsCsv")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("SavedReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "NextRunAtUtc")
                        .HasDatabaseName("IX_ReportSchedules_Active_NextRun");

                    b.ToTable("ReportSchedules", "config");
                });

            modelBuilder.Entity("JobPlatform.Reporting.Domain.ReportTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Revision")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.ToTable("ReportTemplates", "config");
                });

            modelBuilder.Entity("JobPlatform.Reporting.Domain.SavedReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RetainUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived", "RetainUntilUtc")
                        .HasDatabaseName("IX_SavedReports_Retention");

                    b.HasIndex("OwnerId", "CreatedAtUtc")
                        .HasDatabaseName("IX_SavedReports_Owner_Created");

                    b.ToTable("SavedReports", "config");
                });
#pragma warning restore 612, 618
        }
    }
}
