<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>JobPlatform.JobSeekerProfile.Api.IntegrationTests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/Services/JobSeekerProfile/JobPlatform.JobSeekerProfile.Api/JobPlatform.JobSeekerProfile.Api.csproj" />
    <ProjectReference Include="../../../src/Services/JobSeekerProfile/JobPlatform.JobSeekerProfile.Infrastructure/JobPlatform.JobSeekerProfile.Infrastructure.csproj" />
    <ProjectReference Include="../../../src/Services/JobSeekerProfile/JobPlatform.JobSeekerProfile.Application/JobPlatform.JobSeekerProfile.Application.csproj" />
    <ProjectReference Include="../../../src/Services/JobSeekerProfile/JobPlatform.JobSeekerProfile.Domain/JobPlatform.JobSeekerProfile.Domain.csproj" />
    <ProjectReference Include="../../../src/BuildingBlocks/JobPlatform.SharedKernel/JobPlatform.SharedKernel.csproj" />
    <ProjectReference Include="../../../src/BuildingBlocks/JobPlatform.BuildingBlocks.Infrastructure/JobPlatform.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="../../../src/BuildingBlocks/JobPlatform.BuildingBlocks.Api/JobPlatform.BuildingBlocks.Api.csproj" />
    <ProjectReference Include="../../BuildingBlocks/JobPlatform.TestSupport/JobPlatform.TestSupport.csproj" />
  </ItemGroup>
</Project>