// <auto-generated />
using System;
using JobPlatform.AccountIdentity.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobPlatform.AccountIdentity.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260919082234_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobPlatform.AccountIdentity.Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<DateTime?>("EmailVerificationExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailVerificationTokenHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EmailVerifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FirstFailedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdentityKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("ExternalIdentityKey");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MfaEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MfaEnrolledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MfaSecret")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PasswordChangedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("PasswordPolicyVersion")
                        .HasColumnType("int");

                    b.Property<int>("RegistrationLevel")
                        .HasColumnType("int");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Standing")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("ActorType", "Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_Accounts_ActorType_Email")
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("ActorType", "IdentityKey")
                        .IsUnique()
                        .HasDatabaseName("UQ_Accounts_ActorType_ExternalIdentityKey")
                        .HasFilter("[ExternalIdentityKey] IS NOT NULL");

                    b.HasIndex("ActorType", "Mobile")
                        .IsUnique()
                        .HasDatabaseName("UQ_Accounts_ActorType_Mobile");

                    b.ToTable("Accounts", "identity");
                });

            modelBuilder.Entity("JobPlatform.AccountIdentity.Domain.ApiCredentials.ApiCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("FailedAuthAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FirstFailedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpWhitelist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IpWhitelistJson");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Limits")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LimitsJson");

                    b.Property<Guid>("PartnerAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("KeyId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ApiCredentials_KeyId");

                    b.HasIndex("PartnerAccountId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ApiCredentials_OneActivePerPartner")
                        .HasFilter("[Status] = 'Active'");

                    b.ToTable("ApiCredentials", "identity");
                });

            modelBuilder.Entity("JobPlatform.AccountIdentity.Domain.Consent.PrivacyConsent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Choices")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ChoicesJson");

                    b.Property<DateTime>("DecidedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("GuestId", "PolicyVersion")
                        .IsUnique()
                        .HasDatabaseName("UQ_PrivacyConsents_GuestId_PolicyVersion");

                    b.ToTable("PrivacyConsents", "identity");
                });

            modelBuilder.Entity("JobPlatform.AccountIdentity.Domain.PasswordPolicies.PasswordPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MinLength")
                        .HasColumnType("int");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("int");

                    b.Property<bool>("RequireDigit")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireLower")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireUpper")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.ToTable("PasswordPolicy", "identity");
                });

            modelBuilder.Entity("JobPlatform.AccountIdentity.Domain.Rbac.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Roles_Name");

                    b.ToTable("Roles", "identity");
                });

            modelBuilder.Entity("JobPlatform.AccountIdentity.Domain.Sessions.SessionTimeoutSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdleTimeoutMinutes")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SettingVersion")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.ToTable("SessionSettings", "identity");
                });

            modelBuilder.Entity("JobPlatform.AccountIdentity.Infrastructure.Persistence.AccessLogRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AtUtc")
                        .HasDatabaseName("IX_AccessLog_At");

                    b.HasIndex("AccountId", "AtUtc")
                        .HasDatabaseName("IX_AccessLog_AccountId_At");

                    b.ToTable("AccessLog", "identity");
                });

            modelBuilder.Entity("JobPlatform.AccountIdentity.Infrastructure.Persistence.SigningKeyRecord", b =>
                {
                    b.Property<string>("Kid")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EncryptedPrivateKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NotAfterUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NotBeforeUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Kid");

                    b.ToTable("SigningKeys", "identity");
                });

            modelBuilder.Entity("JobPlatform.BuildingBlocks.Infrastructure.Persistence.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("NextAttemptUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReceivedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("MessageId", "ConsumerName");

                    b.HasIndex("Status", "NextAttemptUtc")
                        .HasDatabaseName("IX_InboxMessages_Status_NextAttemptUtc");

                    b.ToTable("InboxMessages", "messaging");
                });

            modelBuilder.Entity("JobPlatform.BuildingBlocks.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("AggregateVersion")
                        .HasColumnType("bigint");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("NextAttemptUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextAttemptUtc")
                        .HasDatabaseName("IX_OutboxMessages_Status_NextAttemptUtc");

                    b.ToTable("OutboxMessages", "messaging");
                });

            modelBuilder.Entity("JobPlatform.AccountIdentity.Domain.Accounts.Account", b =>
                {
                    b.OwnsMany("JobPlatform.AccountIdentity.Domain.Accounts.AccountRoleAssignment", "RoleAssignments", b1 =>
                        {
                            b1.Property<Guid>("AccountId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("RoleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("AssignedAtUtc")
                                .HasColumnType("datetime2");

                            b1.HasKey("AccountId", "RoleId");

                            b1.ToTable("AccountRoles", "identity");

                            b1.WithOwner()
                                .HasForeignKey("AccountId");
                        });

                    b.OwnsMany("JobPlatform.AccountIdentity.Domain.Accounts.AccountStatusChange", "StatusHistory", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("AccountId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("AtUtc")
                                .HasColumnType("datetime2");

                            b1.Property<Guid>("By")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("From")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("Reason")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<string>("To")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.HasKey("Id");

                            b1.HasIndex("AccountId", "AtUtc")
                                .HasDatabaseName("IX_AccountStatusHistory_AccountId_AtUtc");

                            b1.ToTable("AccountStatusHistory", "identity");

                            b1.WithOwner()
                                .HasForeignKey("AccountId");
                        });

                    b.OwnsOne("JobPlatform.AccountIdentity.Domain.Accounts.ActivationChallenge", "ActivationChallenge", b1 =>
                        {
                            b1.Property<Guid>("AccountId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Attempts")
                                .HasColumnType("int");

                            b1.Property<string>("CodeHash")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<DateTime>("ExpiresAtUtc")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("IssuedAtUtc")
                                .HasColumnType("datetime2");

                            b1.HasKey("AccountId");

                            b1.ToTable("ActivationChallenges", "identity");

                            b1.WithOwner()
                                .HasForeignKey("AccountId");
                        });

                    b.Navigation("ActivationChallenge");

                    b.Navigation("RoleAssignments");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("JobPlatform.AccountIdentity.Domain.Rbac.Role", b =>
                {
                    b.OwnsMany("JobPlatform.AccountIdentity.Domain.Rbac.RolePermission", "Permissions", b1 =>
                        {
                            b1.Property<Guid>("RoleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Permission")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("RoleId", "Permission");

                            b1.ToTable("RolePermissions", "identity");

                            b1.WithOwner()
                                .HasForeignKey("RoleId");
                        });

                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
