// <auto-generated />
using System;
using JobPlatform.EmployerOnboarding.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobPlatform.EmployerOnboarding.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EmployerOnboardingDbContext))]
    [Migration("20260927100113_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("employer")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobPlatform.BuildingBlocks.Infrastructure.Persistence.IdempotencyKeyRecord", b =>
                {
                    b.Property<string>("Scope")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Scope", "Key");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("IX_IdempotencyKeys_ExpiresAtUtc");

                    b.ToTable("IdempotencyKeys", "messaging");
                });

            modelBuilder.Entity("JobPlatform.BuildingBlocks.Infrastructure.Persistence.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("NextAttemptUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReceivedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("MessageId", "ConsumerName");

                    b.HasIndex("Status", "NextAttemptUtc")
                        .HasDatabaseName("IX_InboxMessages_Status_NextAttemptUtc");

                    b.ToTable("InboxMessages", "messaging");
                });

            modelBuilder.Entity("JobPlatform.BuildingBlocks.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("AggregateVersion")
                        .HasColumnType("bigint");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("NextAttemptUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextAttemptUtc")
                        .HasDatabaseName("IX_OutboxMessages_Status_NextAttemptUtc");

                    b.ToTable("OutboxMessages", "messaging");
                });

            modelBuilder.Entity("JobPlatform.EmployerOnboarding.Domain.BadgeAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CausedByMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Change")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("EmployerStandingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmployerStandingId", "AtUtc")
                        .HasDatabaseName("IX_BadgeAudit_Standing_At");

                    b.ToTable("BadgeAudit", "employer");
                });

            modelBuilder.Entity("JobPlatform.EmployerOnboarding.Domain.CompanyMediaAndDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployerAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPrimaryLogo")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("EmployerAccountId")
                        .HasDatabaseName("IX_CompanyMedia_EmployerAccountId");

                    b.ToTable("CompanyMedia", "employer");
                });

            modelBuilder.Entity("JobPlatform.EmployerOnboarding.Domain.EmployerRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyIdentity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CompanyIdentityJson");

                    b.Property<Guid>("EmployerAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Level2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Level2Json");

                    b.Property<DateTime>("OpenedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("EmployerAccountId")
                        .IsUnique()
                        .HasDatabaseName("UQ_EmployerRegistrations_EmployerAccountId");

                    b.ToTable("EmployerRegistrations", "employer");
                });

            modelBuilder.Entity("JobPlatform.EmployerOnboarding.Domain.EmployerStanding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AdmissionApproved")
                        .HasColumnType("bit");

                    b.Property<Guid>("EmployerAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<long>("LastVerificationEventVersion")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("VerifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("EmployerAccountId")
                        .IsUnique()
                        .HasDatabaseName("UQ_EmployerStandings_EmployerAccountId");

                    b.ToTable("EmployerStandings", "employer");
                });

            modelBuilder.Entity("JobPlatform.EmployerOnboarding.Domain.KnownAccount", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActiveSinceUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("AccountId");

                    b.ToTable("KnownAccounts", "employer");
                });

            modelBuilder.Entity("JobPlatform.EmployerOnboarding.Domain.BadgeAuditEntry", b =>
                {
                    b.HasOne("JobPlatform.EmployerOnboarding.Domain.EmployerStanding", null)
                        .WithMany("BadgeAudit")
                        .HasForeignKey("EmployerStandingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JobPlatform.EmployerOnboarding.Domain.CompanyMediaAndDocument", b =>
                {
                    b.OwnsOne("JobPlatform.EmployerOnboarding.Domain.FileReference", "File", b1 =>
                        {
                            b1.Property<Guid>("CompanyMediaAndDocumentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("ContentType");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(260)
                                .HasColumnType("nvarchar(260)")
                                .HasColumnName("FileName");

                            b1.Property<string>("Sha256")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("Sha256");

                            b1.Property<long>("SizeBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("SizeBytes");

                            b1.Property<string>("StorageKey")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("StorageKey");

                            b1.HasKey("CompanyMediaAndDocumentId");

                            b1.ToTable("CompanyMedia", "employer");

                            b1.WithOwner()
                                .HasForeignKey("CompanyMediaAndDocumentId");
                        });

                    b.Navigation("File")
                        .IsRequired();
                });

            modelBuilder.Entity("JobPlatform.EmployerOnboarding.Domain.EmployerStanding", b =>
                {
                    b.Navigation("BadgeAudit");
                });
#pragma warning restore 612, 618
        }
    }
}
