// <auto-generated />
using System;
using JobPlatform.ExternalIntegration.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobPlatform.ExternalIntegration.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ExternalIntegrationDbContext))]
    partial class ExternalIntegrationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("extint")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobPlatform.BuildingBlocks.Infrastructure.Persistence.IdempotencyKeyRecord", b =>
                {
                    b.Property<string>("Scope")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Scope", "Key");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("IX_IdempotencyKeys_ExpiresAtUtc");

                    b.ToTable("IdempotencyKeys", "messaging");
                });

            modelBuilder.Entity("JobPlatform.BuildingBlocks.Infrastructure.Persistence.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("NextAttemptUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReceivedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("MessageId", "ConsumerName");

                    b.HasIndex("Status", "NextAttemptUtc")
                        .HasDatabaseName("IX_InboxMessages_Status_NextAttemptUtc");

                    b.ToTable("InboxMessages", "messaging");
                });

            modelBuilder.Entity("JobPlatform.BuildingBlocks.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("AggregateVersion")
                        .HasColumnType("bigint");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("NextAttemptUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextAttemptUtc")
                        .HasDatabaseName("IX_OutboxMessages_Status_NextAttemptUtc");

                    b.ToTable("OutboxMessages", "messaging");
                });

            modelBuilder.Entity("JobPlatform.ExternalIntegration.Domain.ApiSchemaAccessLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApiVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.Property<DateTime>("ViewedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ViewedAtUtc")
                        .HasDatabaseName("IX_ApiSchemaAccessLogs_ViewedAt");

                    b.ToTable("ApiSchemaAccessLogs", "extint");
                });

            modelBuilder.Entity("JobPlatform.ExternalIntegration.Domain.ApiVersion", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("AcceptedFormats")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AcceptedFormatsJson");

                    b.Property<DateTime?>("DeprecatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime?>("SunsetAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.ToTable("ApiVersions", "extint");
                });

            modelBuilder.Entity("JobPlatform.ExternalIntegration.Domain.ExternalJobSiteIntegration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdmissionStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("ApprovalBasis")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttributionVisibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid?>("MappingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PartnerAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Sandbox")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("SandboxProvisionedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("PartnerAccountId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Integrations_PartnerAccountId");

                    b.ToTable("Integrations", "extint");
                });

            modelBuilder.Entity("JobPlatform.ExternalIntegration.Domain.JobData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("PlatformJobId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SourceJobId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("SourcePlatformId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Standardized")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StandardizedJson");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid?>("SyncRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("PlatformJobId")
                        .HasDatabaseName("IX_JobData_PlatformJobId");

                    b.HasIndex("SourcePlatformId", "SourceJobId")
                        .IsUnique()
                        .HasDatabaseName("UQ_JobData_SourcePlatform_SourceJob");

                    b.ToTable("JobData", "extint");
                });

            modelBuilder.Entity("JobPlatform.ExternalIntegration.Domain.JobDataMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MappingVersion")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Rules")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RulesJson");

                    b.Property<string>("StandardSchemaVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationId")
                        .IsUnique()
                        .HasDatabaseName("UQ_JobDataMappings_IntegrationId");

                    b.ToTable("JobDataMappings", "extint");
                });

            modelBuilder.Entity("JobPlatform.ExternalIntegration.Domain.JobPostAttribution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Backlink")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("DeadlineUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("JobDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlatformJobId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SourcePlatformName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SyncState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("JobDataId")
                        .IsUnique()
                        .HasDatabaseName("UQ_JobPostAttributions_JobDataId");

                    b.HasIndex("PlatformJobId")
                        .IsUnique()
                        .HasDatabaseName("UQ_JobPostAttributions_PlatformJobId");

                    b.ToTable("JobPostAttributions", "extint");
                });

            modelBuilder.Entity("JobPlatform.ExternalIntegration.Domain.KnownPartnerAccount", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActiveSinceUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("AccountId");

                    b.ToTable("KnownPartnerAccounts", "extint");
                });

            modelBuilder.Entity("JobPlatform.ExternalIntegration.Domain.PartnerCredential", b =>
                {
                    b.Property<Guid>("ApiCredentialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("LastEventVersion")
                        .HasColumnType("bigint");

                    b.HasKey("ApiCredentialId");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("IX_PartnerCredentials_AccountId");

                    b.ToTable("PartnerCredentials", "extint");
                });

            modelBuilder.Entity("JobPlatform.ExternalIntegration.Domain.SoftwareInterfaceConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_SoftwareInterfaces_Category_Name");

                    b.ToTable("SoftwareInterfaces", "extint");
                });

            modelBuilder.Entity("JobPlatform.ExternalIntegration.Domain.SyncRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Accepted")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("ExternalJobSiteIntegrationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MappingVersion")
                        .HasColumnType("int");

                    b.Property<int>("Received")
                        .HasColumnType("int");

                    b.Property<int>("Rejected")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalJobSiteIntegrationId", "StartedAtUtc")
                        .HasDatabaseName("IX_SyncRuns_Integration_StartedAt");

                    b.ToTable("SyncRuns", "extint");
                });

            modelBuilder.Entity("JobPlatform.ExternalIntegration.Domain.ExternalJobSiteIntegration", b =>
                {
                    b.OwnsOne("JobPlatform.ExternalIntegration.Domain.SourcePlatform", "SourcePlatform", b1 =>
                        {
                            b1.Property<Guid>("ExternalJobSiteIntegrationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("BaseUrl")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("BaseUrl");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("SourcePlatformId");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("SourcePlatformName");

                            b1.HasKey("ExternalJobSiteIntegrationId");

                            b1.HasIndex("Id")
                                .IsUnique()
                                .HasDatabaseName("UQ_Integrations_SourcePlatformId");

                            b1.ToTable("Integrations", "extint");

                            b1.WithOwner()
                                .HasForeignKey("ExternalJobSiteIntegrationId");
                        });

                    b.OwnsOne("JobPlatform.ExternalIntegration.Domain.SyncModels", "Models", b1 =>
                        {
                            b1.Property<Guid>("ExternalJobSiteIntegrationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("PullEnabled")
                                .HasColumnType("bit")
                                .HasColumnName("PullEnabled");

                            b1.Property<bool>("PushEnabled")
                                .HasColumnType("bit")
                                .HasColumnName("PushEnabled");

                            b1.HasKey("ExternalJobSiteIntegrationId");

                            b1.ToTable("Integrations", "extint");

                            b1.WithOwner()
                                .HasForeignKey("ExternalJobSiteIntegrationId");
                        });

                    b.OwnsOne("JobPlatform.ExternalIntegration.Domain.SyncSchedule", "Schedule", b1 =>
                        {
                            b1.Property<Guid>("ExternalJobSiteIntegrationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Cron")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("SyncCron");

                            b1.Property<string>("Mode")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)")
                                .HasColumnName("SyncMode");

                            b1.HasKey("ExternalJobSiteIntegrationId");

                            b1.ToTable("Integrations", "extint");

                            b1.WithOwner()
                                .HasForeignKey("ExternalJobSiteIntegrationId");
                        });

                    b.Navigation("Models")
                        .IsRequired();

                    b.Navigation("Schedule")
                        .IsRequired();

                    b.Navigation("SourcePlatform")
                        .IsRequired();
                });

            modelBuilder.Entity("JobPlatform.ExternalIntegration.Domain.SyncRun", b =>
                {
                    b.HasOne("JobPlatform.ExternalIntegration.Domain.ExternalJobSiteIntegration", null)
                        .WithMany("SyncRuns")
                        .HasForeignKey("ExternalJobSiteIntegrationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JobPlatform.ExternalIntegration.Domain.ExternalJobSiteIntegration", b =>
                {
                    b.Navigation("SyncRuns");
                });
#pragma warning restore 612, 618
        }
    }
}
