<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>JobPlatform.CandidateSourcing.Api</AssemblyName>
    <RootNamespace>JobPlatform.CandidateSourcing.Api</RootNamespace>
    <UserSecretsId>jobplatform-candidate-sourcing</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\JobPlatform.CandidateSourcing.Application\JobPlatform.CandidateSourcing.Application.csproj" />
    <ProjectReference Include="..\JobPlatform.CandidateSourcing.Infrastructure\JobPlatform.CandidateSourcing.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\JobPlatform.SharedKernel\JobPlatform.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\JobPlatform.BuildingBlocks.Infrastructure\JobPlatform.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\JobPlatform.BuildingBlocks.Api\JobPlatform.BuildingBlocks.Api.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="JobPlatform.CandidateSourcing.Api.IntegrationTests" />
    <InternalsVisibleTo Include="JobPlatform.CandidateSourcing.ArchitectureTests" />
  </ItemGroup>
</Project>