<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>JobPlatform.BuildingBlocks.Infrastructure</AssemblyName>
    <RootNamespace>JobPlatform.BuildingBlocks.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="RabbitMQ.Client" />
    <PackageReference Include="StackExchange.Redis" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\JobPlatform.SharedKernel\JobPlatform.SharedKernel.csproj" />
  </ItemGroup>
</Project>
