<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>JobPlatform.CandidateSourcing.Infrastructure.IntegrationTests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/Services/CandidateSourcing/JobPlatform.CandidateSourcing.Api/JobPlatform.CandidateSourcing.Api.csproj" />
    <ProjectReference Include="../../../src/Services/CandidateSourcing/JobPlatform.CandidateSourcing.Infrastructure/JobPlatform.CandidateSourcing.Infrastructure.csproj" />
    <ProjectReference Include="../../../src/Services/CandidateSourcing/JobPlatform.CandidateSourcing.Application/JobPlatform.CandidateSourcing.Application.csproj" />
    <ProjectReference Include="../../../src/Services/CandidateSourcing/JobPlatform.CandidateSourcing.Domain/JobPlatform.CandidateSourcing.Domain.csproj" />
    <ProjectReference Include="../../../src/BuildingBlocks/JobPlatform.SharedKernel/JobPlatform.SharedKernel.csproj" />
    <ProjectReference Include="../../../src/BuildingBlocks/JobPlatform.BuildingBlocks.Infrastructure/JobPlatform.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="../../../src/BuildingBlocks/JobPlatform.BuildingBlocks.Api/JobPlatform.BuildingBlocks.Api.csproj" />
    <ProjectReference Include="../../BuildingBlocks/JobPlatform.TestSupport/JobPlatform.TestSupport.csproj" />
  </ItemGroup>
</Project>