<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>JobPlatform.AccountIdentity.Application.UnitTests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/Services/AccountIdentity/JobPlatform.AccountIdentity.Application/JobPlatform.AccountIdentity.Application.csproj" />
    <ProjectReference Include="../../../src/Services/AccountIdentity/JobPlatform.AccountIdentity.Domain/JobPlatform.AccountIdentity.Domain.csproj" />
    <ProjectReference Include="../../../src/BuildingBlocks/JobPlatform.SharedKernel/JobPlatform.SharedKernel.csproj" />
    <ProjectReference Include="../../../src/BuildingBlocks/JobPlatform.BuildingBlocks.Infrastructure/JobPlatform.BuildingBlocks.Infrastructure.csproj" />
  </ItemGroup>
</Project>
