<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>JobPlatform.ExternalIntegration.Domain.UnitTests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/Services/ExternalIntegration/JobPlatform.ExternalIntegration.Domain/JobPlatform.ExternalIntegration.Domain.csproj" />
    <ProjectReference Include="../../../src/BuildingBlocks/JobPlatform.SharedKernel/JobPlatform.SharedKernel.csproj" />
  </ItemGroup>
</Project>