<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>JobPlatform.AuditLogging.Api</AssemblyName>
    <RootNamespace>JobPlatform.AuditLogging.Api</RootNamespace>
    <UserSecretsId>jobplatform-audit-logging</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\JobPlatform.AuditLogging.Application\JobPlatform.AuditLogging.Application.csproj" />
    <ProjectReference Include="..\JobPlatform.AuditLogging.Infrastructure\JobPlatform.AuditLogging.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\JobPlatform.SharedKernel\JobPlatform.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\JobPlatform.BuildingBlocks.Infrastructure\JobPlatform.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\JobPlatform.BuildingBlocks.Api\JobPlatform.BuildingBlocks.Api.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="JobPlatform.AuditLogging.Api.IntegrationTests" />
    <InternalsVisibleTo Include="JobPlatform.AuditLogging.ArchitectureTests" />
  </ItemGroup>
</Project>