// <auto-generated />
using System;
using JobPlatform.JobPosting.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobPlatform.JobPosting.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(JobPostingDbContext))]
    [Migration("20260927062730_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("jobs")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobPlatform.BuildingBlocks.Infrastructure.Persistence.IdempotencyKeyRecord", b =>
                {
                    b.Property<string>("Scope")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Scope", "Key");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("IX_IdempotencyKeys_ExpiresAtUtc");

                    b.ToTable("IdempotencyKeys", "messaging");
                });

            modelBuilder.Entity("JobPlatform.BuildingBlocks.Infrastructure.Persistence.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("NextAttemptUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReceivedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("MessageId", "ConsumerName");

                    b.HasIndex("Status", "NextAttemptUtc")
                        .HasDatabaseName("IX_InboxMessages_Status_NextAttemptUtc");

                    b.ToTable("InboxMessages", "messaging");
                });

            modelBuilder.Entity("JobPlatform.BuildingBlocks.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("AggregateVersion")
                        .HasColumnType("bigint");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("NextAttemptUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextAttemptUtc")
                        .HasDatabaseName("IX_OutboxMessages_Status_NextAttemptUtc");

                    b.ToTable("OutboxMessages", "messaging");
                });

            modelBuilder.Entity("JobPlatform.JobPosting.Domain.FavoriteJobList", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JobPostingIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JobPostingIdsJson");

                    b.Property<Guid>("OwnerAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAccountId")
                        .IsUnique()
                        .HasDatabaseName("UQ_FavoriteJobLists_Owner");

                    b.ToTable("FavoriteJobLists", "jobs");
                });

            modelBuilder.Entity("JobPlatform.JobPosting.Domain.InterestedListEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OwnerAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ReferenceJson");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAccountId")
                        .HasDatabaseName("IX_InterestedListEntries_Owner");

                    b.ToTable("InterestedListEntries", "jobs");
                });

            modelBuilder.Entity("JobPlatform.JobPosting.Domain.JobPosting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AdminSuspended")
                        .HasColumnType("bit");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EducationLevelValue")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("EducationLevel");

                    b.Property<Guid?>("EmployerAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JobLink")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("MaxExperienceYears")
                        .HasColumnType("int");

                    b.Property<int?>("MinExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("OtherFields")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OtherFieldsJson");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequiredLanguages")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RequiredLanguagesJson");

                    b.Property<string>("RequiredTraining")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RequiredTrainingJson");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SkillsJson");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SuspendReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TaxonomyVersion")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.Property<string>("WorkFormat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryCode")
                        .HasDatabaseName("IX_JobPostings_Category");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_JobPostings_Status");

                    b.HasIndex("EmployerAccountId", "ContentHash")
                        .HasDatabaseName("IX_JobPostings_Employer_ContentHash");

                    b.ToTable("JobPostings", "jobs");
                });

            modelBuilder.Entity("JobPlatform.JobPosting.Domain.SavedSearch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Criteria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CriteriaJson");

                    b.Property<string>("CriteriaHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("LastEvaluatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NotifyOnMatch")
                        .HasColumnType("bit");

                    b.Property<Guid>("OwnerAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("NotifyOnMatch")
                        .HasDatabaseName("IX_SavedSearches_NotifyOnMatch");

                    b.HasIndex("OwnerAccountId", "CriteriaHash")
                        .IsUnique()
                        .HasDatabaseName("UQ_SavedSearches_Owner_Hash");

                    b.ToTable("SavedSearches", "jobs");
                });

            modelBuilder.Entity("JobPlatform.JobPosting.Domain.JobPosting", b =>
                {
                    b.OwnsOne("JobPlatform.JobPosting.Domain.ApplicationDeadline", "Deadline", b1 =>
                        {
                            b1.Property<Guid>("JobPostingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("AutoClose")
                                .HasColumnType("bit")
                                .HasColumnName("AutoClose");

                            b1.Property<DateTime>("DateUtc")
                                .HasColumnType("datetime2")
                                .HasColumnName("DeadlineDate");

                            b1.HasKey("JobPostingId");

                            b1.ToTable("JobPostings", "jobs");

                            b1.WithOwner()
                                .HasForeignKey("JobPostingId");
                        });

                    b.OwnsOne("JobPlatform.JobPosting.Domain.JobLocation", "Location", b1 =>
                        {
                            b1.Property<Guid>("JobPostingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("City");

                            b1.Property<string>("Governorate")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Governorate");

                            b1.HasKey("JobPostingId");

                            b1.ToTable("JobPostings", "jobs");

                            b1.WithOwner()
                                .HasForeignKey("JobPostingId");
                        });

                    b.OwnsOne("JobPlatform.SharedKernel.Common.ValueObjects.LocalizedText", "Summary", b1 =>
                        {
                            b1.Property<Guid>("JobPostingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(5000)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("SummaryAr");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(5000)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("SummaryEn");

                            b1.HasKey("JobPostingId");

                            b1.ToTable("JobPostings", "jobs");

                            b1.WithOwner()
                                .HasForeignKey("JobPostingId");
                        });

                    b.OwnsOne("JobPlatform.SharedKernel.Common.ValueObjects.LocalizedText", "Title", b1 =>
                        {
                            b1.Property<Guid>("JobPostingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("TitleAr");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("TitleEn");

                            b1.HasKey("JobPostingId");

                            b1.ToTable("JobPostings", "jobs");

                            b1.WithOwner()
                                .HasForeignKey("JobPostingId");
                        });

                    b.OwnsOne("JobPlatform.JobPosting.Domain.JobSource", "Source", b1 =>
                        {
                            b1.Property<Guid>("JobPostingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("AttributionPublic")
                                .HasColumnType("bit")
                                .HasColumnName("SourceAttributionPublic");

                            b1.Property<string>("BacklinkUrl")
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("SourceBacklinkUrl");

                            b1.Property<string>("PlatformJobId")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("SourcePlatformJobId");

                            b1.Property<string>("SourceName")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("SourceName");

                            b1.Property<Guid?>("SourcePlatformId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("SourcePlatformId");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("SourceType");

                            b1.HasKey("JobPostingId");

                            b1.HasIndex("PlatformJobId")
                                .HasDatabaseName("IX_JobPostings_Source_PlatformJobId");

                            b1.ToTable("JobPostings", "jobs");

                            b1.WithOwner()
                                .HasForeignKey("JobPostingId");
                        });

                    b.OwnsOne("JobPlatform.JobPosting.Domain.JobVisibility", "Visibility", b1 =>
                        {
                            b1.Property<Guid>("JobPostingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Scope")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("VisibilityScope");

                            b1.Property<string>("TargetJobSeekerIds")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("VisibilityTargetJson");

                            b1.HasKey("JobPostingId");

                            b1.ToTable("JobPostings", "jobs");

                            b1.WithOwner()
                                .HasForeignKey("JobPostingId");
                        });

                    b.OwnsOne("JobPlatform.JobPosting.Domain.SalaryRange", "Salary", b1 =>
                        {
                            b1.Property<Guid>("JobPostingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("SalaryCurrency");

                            b1.Property<decimal?>("Max")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("SalaryMax");

                            b1.Property<decimal?>("Min")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("SalaryMin");

                            b1.HasKey("JobPostingId");

                            b1.ToTable("JobPostings", "jobs");

                            b1.WithOwner()
                                .HasForeignKey("JobPostingId");
                        });

                    b.Navigation("Deadline")
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Salary");

                    b.Navigation("Source")
                        .IsRequired();

                    b.Navigation("Summary")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();

                    b.Navigation("Visibility")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
