<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>JobPlatform.AiMatching.Infrastructure</AssemblyName>
    <RootNamespace>JobPlatform.AiMatching.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\JobPlatform.AiMatching.Application\JobPlatform.AiMatching.Application.csproj" />
    <ProjectReference Include="..\JobPlatform.AiMatching.Domain\JobPlatform.AiMatching.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\JobPlatform.SharedKernel\JobPlatform.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\JobPlatform.BuildingBlocks.Infrastructure\JobPlatform.BuildingBlocks.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="JobPlatform.AiMatching.Infrastructure.IntegrationTests" />
    <InternalsVisibleTo Include="JobPlatform.AiMatching.Api.IntegrationTests" />
  </ItemGroup>
</Project>
