<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>JobPlatform.HelpContent.Api</AssemblyName>
    <RootNamespace>JobPlatform.HelpContent.Api</RootNamespace>
    <UserSecretsId>jobplatform-help-content</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\JobPlatform.HelpContent.Application\JobPlatform.HelpContent.Application.csproj" />
    <ProjectReference Include="..\JobPlatform.HelpContent.Infrastructure\JobPlatform.HelpContent.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\JobPlatform.SharedKernel\JobPlatform.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\JobPlatform.BuildingBlocks.Infrastructure\JobPlatform.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\JobPlatform.BuildingBlocks.Api\JobPlatform.BuildingBlocks.Api.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="JobPlatform.HelpContent.Api.IntegrationTests" />
    <InternalsVisibleTo Include="JobPlatform.HelpContent.ArchitectureTests" />
  </ItemGroup>
</Project>