<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>JobPlatform.BuildingBlocks.Infrastructure.UnitTests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/BuildingBlocks/JobPlatform.SharedKernel/JobPlatform.SharedKernel.csproj" />
    <ProjectReference Include="../../../src/BuildingBlocks/JobPlatform.BuildingBlocks.Infrastructure/JobPlatform.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="../JobPlatform.TestSupport/JobPlatform.TestSupport.csproj" />
  </ItemGroup>
</Project>
