// <auto-generated />
using System;
using JobPlatform.GovernmentIntegration.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobPlatform.GovernmentIntegration.Infrastructure.Migrations
{
    [DbContext(typeof(GovernmentIntegrationDbContext))]
    partial class GovernmentIntegrationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("govint")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobPlatform.BuildingBlocks.Infrastructure.Persistence.IdempotencyKeyRecord", b =>
                {
                    b.Property<string>("Scope")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Scope", "Key");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("IX_IdempotencyKeys_ExpiresAtUtc");

                    b.ToTable("IdempotencyKeys", "messaging");
                });

            modelBuilder.Entity("JobPlatform.BuildingBlocks.Infrastructure.Persistence.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("NextAttemptUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReceivedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("MessageId", "ConsumerName");

                    b.HasIndex("Status", "NextAttemptUtc")
                        .HasDatabaseName("IX_InboxMessages_Status_NextAttemptUtc");

                    b.ToTable("InboxMessages", "messaging");
                });

            modelBuilder.Entity("JobPlatform.BuildingBlocks.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("AggregateVersion")
                        .HasColumnType("bigint");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("NextAttemptUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextAttemptUtc")
                        .HasDatabaseName("IX_OutboxMessages_Status_NextAttemptUtc");

                    b.ToTable("OutboxMessages", "messaging");
                });

            modelBuilder.Entity("JobPlatform.GovernmentIntegration.Domain.DataQuality", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DuplicatesRemoved")
                        .HasColumnType("int");

                    b.Property<int>("FormatsStandardized")
                        .HasColumnType("int");

                    b.Property<int>("IssuesResolved")
                        .HasColumnType("int");

                    b.Property<Guid>("MigrationRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RecordsChecked")
                        .HasColumnType("int");

                    b.Property<int>("RecordsRejected")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SnapshotVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("IX_DataQuality_BatchId");

                    b.ToTable("DataQuality", "govint");
                });

            modelBuilder.Entity("JobPlatform.GovernmentIntegration.Domain.EducationalCredentialVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("RetentionExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("IX_EducationalCredentialVerifications_SubjectId");

                    b.ToTable("EducationalCredentialVerifications", "govint");
                });

            modelBuilder.Entity("JobPlatform.GovernmentIntegration.Domain.EmployerVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DecidedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DecidedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployerAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FailureReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Submission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SubmissionJson");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("EmployerAccountId", "State")
                        .HasDatabaseName("IX_EmployerVerifications_EmployerAccountId_State");

                    b.ToTable("EmployerVerifications", "govint");
                });

            modelBuilder.Entity("JobPlatform.GovernmentIntegration.Domain.GovernmentDataAccessLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SubjectRef")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("IX_GovernmentDataAccessLog_OccurredAtUtc");

                    b.ToTable("GovernmentDataAccessLog", "govint");
                });

            modelBuilder.Entity("JobPlatform.GovernmentIntegration.Domain.GovernmentSourceConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthMethod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("int");

                    b.Property<string>("CredentialRef")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime?>("LastSuccessfulSyncAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("Source")
                        .IsUnique()
                        .HasDatabaseName("UQ_GovernmentSourceConnections_Source");

                    b.ToTable("GovernmentSourceConnections", "govint");
                });

            modelBuilder.Entity("JobPlatform.GovernmentIntegration.Domain.GovernmentVerificationData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ImportedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("RetentionExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("VerifiedFields")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VerifiedFieldsJson");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("RetentionExpiresAtUtc")
                        .HasDatabaseName("IX_GovernmentVerificationData_RetentionExpiresAtUtc");

                    b.ToTable("GovernmentVerificationData", "govint");
                });

            modelBuilder.Entity("JobPlatform.GovernmentIntegration.Domain.IdentityVerificationData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("RetentionExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("UnverifiedReason")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.ToTable("IdentityVerifications", "govint");
                });

            modelBuilder.Entity("JobPlatform.GovernmentIntegration.Domain.KnownAccount", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("LastEventVersion")
                        .HasColumnType("bigint");

                    b.HasKey("AccountId");

                    b.ToTable("KnownAccounts", "govint");
                });

            modelBuilder.Entity("JobPlatform.GovernmentIntegration.Domain.LegacyData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MappedPayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MigrationBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MigrationRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SourcePayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceRecordId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("ValidationErrors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ValidationErrorsJson");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("MigrationBatchId", "Stage")
                        .HasDatabaseName("IX_LegacyData_MigrationBatchId_Stage");

                    b.HasIndex("SourceSystem", "SourceRecordId")
                        .IsUnique()
                        .HasDatabaseName("UQ_LegacyData_SourceSystem_SourceRecordId");

                    b.ToTable("LegacyData", "govint");
                });

            modelBuilder.Entity("JobPlatform.GovernmentIntegration.Domain.MigrationLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("MigrationRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("MigrationRunId");

                    b.ToTable("MigrationLog", "govint");
                });

            modelBuilder.Entity("JobPlatform.GovernmentIntegration.Domain.MigrationPhase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("MigrationRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("TestOutcome")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("MigrationRunId");

                    b.ToTable("MigrationPhases", "govint");
                });

            modelBuilder.Entity("JobPlatform.GovernmentIntegration.Domain.MigrationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentPhaseIndex")
                        .HasColumnType("int");

                    b.Property<Guid>("InitiatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("AggregateVersion");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_MigrationRuns_Status");

                    b.ToTable("MigrationRuns", "govint");
                });

            modelBuilder.Entity("JobPlatform.GovernmentIntegration.Domain.VerificationAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptNo")
                        .HasColumnType("int");

                    b.Property<Guid?>("EmployerVerificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployerVerificationId", "AttemptNo")
                        .IsUnique()
                        .HasDatabaseName("UQ_EmployerVerificationAttempts_Verification_AttemptNo")
                        .HasFilter("[EmployerVerificationId] IS NOT NULL");

                    b.ToTable("EmployerVerificationAttempts", "govint");
                });

            modelBuilder.Entity("JobPlatform.GovernmentIntegration.Domain.EducationalCredentialVerification", b =>
                {
                    b.OwnsOne("JobPlatform.GovernmentIntegration.Domain.Credential", "Credential", b1 =>
                        {
                            b1.Property<Guid>("EducationalCredentialVerificationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CredentialName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("CredentialName");

                            b1.Property<string>("Institution")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Institution");

                            b1.Property<int>("Year")
                                .HasColumnType("int")
                                .HasColumnName("Year");

                            b1.HasKey("EducationalCredentialVerificationId");

                            b1.ToTable("EducationalCredentialVerifications", "govint");

                            b1.WithOwner()
                                .HasForeignKey("EducationalCredentialVerificationId");
                        });

                    b.Navigation("Credential")
                        .IsRequired();
                });

            modelBuilder.Entity("JobPlatform.GovernmentIntegration.Domain.GovernmentSourceConnection", b =>
                {
                    b.OwnsOne("JobPlatform.GovernmentIntegration.Domain.LastKnownGood", "LastKnownGood", b1 =>
                        {
                            b1.Property<Guid>("GovernmentSourceConnectionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("SnapshotRef")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("LastKnownGoodSnapshotRef");

                            b1.Property<DateTime>("TakenAtUtc")
                                .HasColumnType("datetime2")
                                .HasColumnName("LastKnownGoodTakenAtUtc");

                            b1.HasKey("GovernmentSourceConnectionId");

                            b1.ToTable("GovernmentSourceConnections", "govint");

                            b1.WithOwner()
                                .HasForeignKey("GovernmentSourceConnectionId");
                        });

                    b.Navigation("LastKnownGood");
                });

            modelBuilder.Entity("JobPlatform.GovernmentIntegration.Domain.GovernmentVerificationData", b =>
                {
                    b.OwnsOne("JobPlatform.GovernmentIntegration.Domain.Subject", "Subject", b1 =>
                        {
                            b1.Property<Guid>("GovernmentVerificationDataId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("SubjectId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("SubjectId");

                            b1.Property<string>("SubjectType")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("SubjectType");

                            b1.HasKey("GovernmentVerificationDataId");

                            b1.HasIndex("SubjectType", "SubjectId")
                                .HasDatabaseName("IX_GovernmentVerificationData_Subject");

                            b1.ToTable("GovernmentVerificationData", "govint");

                            b1.WithOwner()
                                .HasForeignKey("GovernmentVerificationDataId");
                        });

                    b.Navigation("Subject")
                        .IsRequired();
                });

            modelBuilder.Entity("JobPlatform.GovernmentIntegration.Domain.IdentityVerificationData", b =>
                {
                    b.OwnsOne("JobPlatform.GovernmentIntegration.Domain.IdentityClaim", "IdentityClaim", b1 =>
                        {
                            b1.Property<Guid>("IdentityVerificationDataId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("DateOfBirth")
                                .HasColumnType("date")
                                .HasColumnName("DateOfBirth");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("FullName");

                            b1.Property<string>("NationalIdReference")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("NationalIdReference");

                            b1.HasKey("IdentityVerificationDataId");

                            b1.ToTable("IdentityVerifications", "govint");

                            b1.WithOwner()
                                .HasForeignKey("IdentityVerificationDataId");
                        });

                    b.OwnsOne("JobPlatform.GovernmentIntegration.Domain.Subject", "Subject", b1 =>
                        {
                            b1.Property<Guid>("IdentityVerificationDataId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("SubjectId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("SubjectId");

                            b1.Property<string>("SubjectType")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("SubjectType");

                            b1.HasKey("IdentityVerificationDataId");

                            b1.HasIndex("SubjectId")
                                .HasDatabaseName("IX_IdentityVerifications_SubjectId");

                            b1.ToTable("IdentityVerifications", "govint");

                            b1.WithOwner()
                                .HasForeignKey("IdentityVerificationDataId");
                        });

                    b.Navigation("IdentityClaim")
                        .IsRequired();

                    b.Navigation("Subject")
                        .IsRequired();
                });

            modelBuilder.Entity("JobPlatform.GovernmentIntegration.Domain.MigrationLogEntry", b =>
                {
                    b.HasOne("JobPlatform.GovernmentIntegration.Domain.MigrationRun", null)
                        .WithMany("Log")
                        .HasForeignKey("MigrationRunId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JobPlatform.GovernmentIntegration.Domain.MigrationPhase", b =>
                {
                    b.HasOne("JobPlatform.GovernmentIntegration.Domain.MigrationRun", null)
                        .WithMany("Phases")
                        .HasForeignKey("MigrationRunId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JobPlatform.GovernmentIntegration.Domain.VerificationAttempt", b =>
                {
                    b.HasOne("JobPlatform.GovernmentIntegration.Domain.EmployerVerification", null)
                        .WithMany("Attempts")
                        .HasForeignKey("EmployerVerificationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JobPlatform.GovernmentIntegration.Domain.EmployerVerification", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("JobPlatform.GovernmentIntegration.Domain.MigrationRun", b =>
                {
                    b.Navigation("Log");

                    b.Navigation("Phases");
                });
#pragma warning restore 612, 618
        }
    }
}
