using JobPlatform.Reporting.Application.DTOs.LaborMarket;
using JobPlatform.SharedKernel.Application.Interfaces.Cqrs;

namespace JobPlatform.Reporting.Application.Queries.LaborMarket;

// US-3.5.2-08 Labor Market Report: one per calendar month, generated by a scheduled job or on demand, idempotent per period.

public sealed record GetLaborMarketReportQuery(string? Period) : EmploymentRequest, IQuery<LaborMarketReportDto>;
